### ISSUE TITLE
ERROR: spawn E2BIG [Line 408]

### ISSUE THREAD

**Issue by luozx112** [naskio/n8n-nodes-python#3]
when there are hundreds items this python node will report the error as below:
![python-node-error](https://user-images.githubusercontent.com/59277630/172535183-2ee0e03d-f058-4032-99cb-ae6385b6def1.png)

**Comment by naskio** [comment]
Hello
Thanks for reporting.
Indeed, we are getting this error when the input is too big
We will fix it as soon as possible

**Comment by naskio** [comment]
Hey @luozx112 
This issue has been fixed (in current version n8n-nodes-python@0.1.4)
It will be also available in the [docker image](https://hub.docker.com/r/naskio/n8n-python) starting from the next release (>0.182.1)
Thanks for reporting

**Comment by luozx112** [comment]
Respect!!!
BTY how can I upgrade it to the new release? cause I found you still not update the docker image of hub.docker.com

**Comment by naskio** [comment]
@luozx112 
it is done now
Just upgrade your docker images 'docker-compose pull'
